-- Populate organizacoes table with military organizations
INSERT INTO organizacoes ("Organização Militar", "Órgão Setorial Responsável", "Sigla da OM") VALUES
('1º Batalhão de Guardas - Organização Militar Diretamente Subordinada ao CML', 'COTER', '1º BG'),
('1º Batalhão de Polícia do Exército', 'COTER', '1º BPE'),
('1º Centro de Gestão, Contabilidade e Finanças do Exército', 'SEF', '1º CGCFEx'),
('1º Depósito de Suprimento', 'COLOG', '1º D Sup'),
('1º Esquadrão de Cavalaria Leve', 'COTER', '1º Esqd C L (AMV)'),
('1º Grupo de Artilharia Antiaérea', 'COTER', '1º GAAAe'),
('21º Grupo de Artilharia de Campanha', 'COTER', '21º GAC'),
('25º Batalhão de Infantaria Pára-quedista', 'COTER', '25º BI Pqdt'),
('27º Batalhão de Infantaria Pára-quedista', 'COTER', '27º BI Pqdt - VILA MILITAR'),
('31º Grupo de Artilharia de Campanha (Escola)', 'COTER', '31° GAC'),
('32º Batalhão de Infantaria Leve de Montanha', 'COTER', '32º BIL Mth'),
('38º Batalhão de Infantaria - Vila Velha/ES', 'COTER', '38º BI - Vila Velha/ES'),
('4º Batalhão de Engenharia de Combate', 'DEC', '4º B E Comb'),
('8º Grupo de Artilharia de Campanha Pára-quedista', 'COTER', '8º GAC'),
('9ª Bateria de Artilharia Antiaérea (Escola)', 'COTER', '9ª Bia AAAe (Es)'),
('Arsenal de Guerra do Rio de Janeiro', 'COLOG', 'AGR'),
('Arquivo Histórico do Exército', 'DECEx', 'AHEx'),
('Academia Militar das Agulhas Negras', 'DECEx', 'AMAN'),
('Arquivo Geral do Comando Militar do Leste', 'COTER', 'Arquivo Geral do CML'),
('Batalhão de Precursores Paraquedistas', 'COTER', 'B PREC PQD'),
('Batalhão de Central de Manutenção e Suprimento', 'COLOG', 'BCMS'),
('Batalhão Escola de Comunicações', 'DCT', 'BEsCOM'),
('Biblioteca do Exército', 'DECEx', 'BiBliEx'),
('Batalhão de Manutenção e Suprimento de Armamento', 'COLOG', 'BMSA'),
('Centro de Estudos de Pessoal e Forte Duque de Caxias', 'DECEx', 'CEP/FDC'),
('Centro General Ernani Ayrosa - Itaipava, Petrópolis-RJ e Vila Popular Manga Larga', 'DGP', 'CGEA/ Vila Popular Manga Larga'),
('Companhia de Comando do Comando Militar do Leste, na Ala Marcílio Dias do PDC', 'COTER', 'Cia C CML'),
('Companhia de Comando da Brigada de Infantaria Pára-quedista', 'COTER', 'Cia Cmdo Bda Inf Pqdt'),
('Comando de Artilharia Divisionária da 1ª Divisão de Exército', 'COTER', 'Cmdo 1º DE'),
('Colégio Militar do Rio de Janeiro', 'DECEx', 'CMRJ'),
('Centro de Preparação de Oficiais da Reserva do Rio de Janeiro', 'DECEx', 'CPOR/RJ'),
('Centro Tecnológico do Exército', 'DCT', 'CTEx'),
('Depósito Central de Munição', 'COLOG', 'DCMun'),
('Destacamento Desportivo da Vila Militar (DDVM)', 'DECEx', 'DDVM'),
('Departamento de Educação e Cultura do Exército', 'DECEx', 'DECEx'),
('Diretoria do Patrimônio Histórico e Cultural do Exército', 'DECEx', 'DPHCEx'),
('Escola de Comando e Estado Maior do Exército', 'DECEx', 'ECEME'),
('Escola de Artilharia de Costa e Antiaérea', 'DECEx', 'EsACosAAe'),
('Escola de Aperfeiçoamento de Oficiais', 'DECEx', 'EsAO'),
('Hospital Central do Exército', 'DGP', 'HCE'),
('Instituto de Defesa Química, Biológica, Radiológica e Nuclear', 'DCT', 'IDQBRN'),
('Instituto Militar de Engenharia', 'DCT', 'IME'),
('Monumento Nacional aos Mortos da Segunda Guerra Mundial', 'DECEx', 'MNMSGM'),
('Organizações Militares Diretamente Subordinadas à Brigada de Infantaria Pára-quedista', 'COTER', 'OMDS da Bda Inf Pqdt'),
('Palácio Duque de Caxias/Ala Marcílio Dias', 'COTER', 'PDC'),
('Policlínica Militar de Niterói', 'DGP', 'PMN'),
('Policlínica Militar do Rio de Janeiro', 'DGP', 'PMRJ'),
('Simulador de Adestramento de Comando e Estado-Maior do Comando Militar do Leste', 'COTER', 'SIMACEM - CA LESTE'),
('Vila Militar da Ilha de Bom Jesus (IBJ)', 'DGP', 'Vila Militar da Ilha de Bom Jesus (IBJ)'),
('Vila Verde - Escola de Aperfeiçoamento de Oficiais', 'DGP', 'Vila Verde - ESAO'),
('Vila Militar de Copacabana - Prefeitura Militar da Zona Sul', 'DGP', 'VMC - PMZS')
ON CONFLICT DO NOTHING;