// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcpnlyqplsfhobhwgoff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjcG5seXFwbHNmaG9iaHdnb2ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDI3MTMsImV4cCI6MjA3NDgxODcxM30.yQiDWEgIhSCjUzNXU5z6emKaqxx3G1h09CrxA-exrds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});